const Identifiers = {
    ArgsMissing: 'argsMissing',
    ArgsUnavailable: 'argsUnavailable',
    ArgumentBooleanError: 'argumentBooleanError',
    ArgumentChannelError: 'argumentChannelError',
    ArgumentDateError: 'argumentDateError',
    ArgumentDateTooEarly: 'argumentDateTooEarly',
    ArgumentDateTooFar: 'argumentDateTooFar',
    ArgumentEnumError: 'argumentEnumError',
    ArgumentFloatError: 'argumentFloatError',
    ArgumentFloatTooSmall: 'argumentFloatTooSmall',
    ArgumentFloatTooBig: 'argumentFloatTooBig',
    ArgumentGuildError: 'argumentGuildError',
    ArgumentHyperlinkError: 'argumentHyperlinkError',
    ArgumentIntegerError: 'argumentIntegerError',
    ArgumentIntegerTooSmall: 'argumentIntegerTooSmall',
    ArgumentIntegerTooBig: 'argumentIntegerTooBig',
    ArgumentMemberError: 'argumentMemberError',
    ArgumentMessageError: 'argumentMessageError',
    ArgumentNumberError: 'argumentNumberError',
    ArgumentNumberTooSmall: 'argumentNumberTooSmall',
    ArgumentNumberTooBig: 'argumentNumberTooBig',
    ArgumentRoleError: 'argumentRoleError',
    ArgumentStringError: 'argumentStringError',
    ArgumentStringTooShort: 'argumentStringTooShort',
    ArgumentStringTooLong: 'argumentStringTooLong',
    ArgumentUserError: 'argumentUserError',
    PreconditionGuildOnly: 'preconditionGuildOnly',
    PreconditionDMOnly: 'preconditionDMOnly',
    PreconditionNSFWOnly: 'preconditionNSFWOnly',
    PreconditionCooldown: 'preconditionCooldown',
    PreconditionMissingPermissions: 'preconditionMissingPermissions',
    PreconditionClientMissingPermissions: 'preconditionClientMissingPermissions',
    CommandDisabled: 'commandDisabled',
    CommandNotFound: 'commandNotFound'
};

module.exports = { Identifiers };
